# Generated by Django 5.1.7 on 2025-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('energy_usage', models.FloatField()),
                ('time_choice', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
